=begin
#myNJ authorization API

#__This document is confidential and proprietary to the State of New Jersey. Do not redistribute it outside your team, and do not post it in any repository or allow it to be incorporated into any artificial intelligence tool, LLM or other database.__  This API is used to manage authorizations for myNJ users to access an agency's application.  It should be called from a user management module in the application, to enable a privileged user to grant and revoke access for other users.  The API allows the privileged user to avoid using the myNJ Role Manager facility for granting and revoking.  The calling application __must__ restrict access to its user management module so that only properly privileged users can use it to cause API calls to be made to myNJ.  The privileged user must have a myNJ account with the role being managed, along with a valid user key (unique identifier) for that role.  The API is not designed or intended for batch operation. 

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for MyNJ::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = MyNJ::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(MyNJ::DefaultApi)
    end
  end

  # unit tests for grant_post
  # Request that myNJ create an authorization to grant a role and associated user key (unique identifier) to a person. If the response object&#x27;s Success property is true, myNJ will have sent an email invitation to the specified address, containing instructions and a one-time authorization code or \&quot;PIN\&quot;. In that case, the caller must store the response AuthID for later revocation or updates. 
  # @param body 
  # @param my_nj_admin_user_key UserKey (unique identifier) in the agency app&#x27;s datastore for the administrator (the person whose actions in the app&#x27;s user administration module triggered this call to the myNJ API). 
  # @param [Hash] opts the optional parameters
  # @return [MynjAuth]
  describe 'grant_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for revoke_post
  # Revoke an existing authorization.  This method must be called when the user identified in the authorization should no longer have access to your application.  Unaccepted invitations can also be revoked. 
  # @param body 
  # @param my_nj_admin_user_key UserKey (unique identifier) in the agency app&#x27;s datastore for the administrator (the person whose actions in the app&#x27;s user administration module triggered this call to the myNJ API). 
  # @param [Hash] opts the optional parameters
  # @return [MynjAuth]
  describe 'revoke_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for status_auth_id_get
  # Get the status and other attributes of an existing authorization. 
  # @param my_nj_admin_user_key UserKey (unique identifier) in the agency app&#x27;s datastore for the administrator (the person whose actions in the app&#x27;s user administration module triggered this call to the myNJ API). 
  # @param auth_id ID of an authorization record returned by a prior call to grant. 
  # @param [Hash] opts the optional parameters
  # @return [MynjAuthStatus]
  describe 'status_auth_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_post
  # Update an existing authorization.  Any fields omitted from the request will not be changed.  The AuthID may not be omitted and cannot be changed.  Some other fields may not be able to be changed, depending on the status of the authorization.  The user key, email and names fields can be changed if the invitation has not been accepted.  Only the user key (unique identifier) can be changed if the invitation has been accepted.  The user key is the basis of single-signon, so its value must match in the user&#x27;s record in the application database and in the user&#x27;s myNJ account.  No fields can be changed if the invitation has been revoked.  It&#x27;s not necessary or possible to update fields other than the user key in an accepted authorization, even if the user&#x27;s name or email address have subsequently changed.  At that point the authorization fields only serve as an audit record of where the invitation was sent and don&#x27;t need to match the user&#x27;s current name or address. 
  # @param body 
  # @param my_nj_admin_user_key UserKey (unique identifier) in the agency app&#x27;s datastore for the administrator (the person whose actions in the app&#x27;s user administration module triggered this call to the myNJ API). 
  # @param [Hash] opts the optional parameters
  # @return [MynjAuth]
  describe 'update_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
