=begin
#myNJ authorization API

#__This document is confidential and proprietary to the State of New Jersey. Do not redistribute it outside your team, and do not post it in any repository or allow it to be incorporated into any artificial intelligence tool, LLM or other database.__  This API is used to manage authorizations for myNJ users to access an agency's application.  It should be called from a user management module in the application, to enable a privileged user to grant and revoke access for other users.  The API allows the privileged user to avoid using the myNJ Role Manager facility for granting and revoking.  The calling application __must__ restrict access to its user management module so that only properly privileged users can use it to cause API calls to be made to myNJ.  The privileged user must have a myNJ account with the role being managed, along with a valid user key (unique identifier) for that role.  The API is not designed or intended for batch operation. 

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

# Common files
require 'my_nj/api_client'
require 'my_nj/api_error'
require 'my_nj/version'
require 'my_nj/configuration'

# Models
require 'my_nj/models/grant'
require 'my_nj/models/mynj_auth'
require 'my_nj/models/mynj_auth_status'
require 'my_nj/models/revoke'
require 'my_nj/models/update'

# APIs
require 'my_nj/api/default_api'

module MyNJ
  class << self
    # Customize default settings for the SDK using block.
    #   MyNJ.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
