=begin
#myNJ authorization API

#__This document is confidential and proprietary to the State of New Jersey. Do not redistribute it outside your team, and do not post it in any repository or allow it to be incorporated into any artificial intelligence tool, LLM or other database.__  This API is used to manage authorizations for myNJ users to access an agency's application.  It should be called from a user management module in the application, to enable a privileged user to grant and revoke access for other users.  The API allows the privileged user to avoid using the myNJ Role Manager facility for granting and revoking.  The calling application __must__ restrict access to its user management module so that only properly privileged users can use it to cause API calls to be made to myNJ.  The privileged user must have a myNJ account with the role being managed, along with a valid user key (unique identifier) for that role.  The API is not designed or intended for batch operation. 

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

module MyNJ
  class ApiError < StandardError
    attr_reader :code, :response_headers, :response_body

    # Usage examples:
    #   ApiError.new
    #   ApiError.new("message")
    #   ApiError.new(:code => 500, :response_headers => {}, :response_body => "")
    #   ApiError.new(:code => 404, :message => "Not Found")
    def initialize(arg = nil)
      if arg.is_a? Hash
        if arg.key?(:message) || arg.key?('message')
          super(arg[:message] || arg['message'])
        else
          super arg
        end

        arg.each do |k, v|
          instance_variable_set "@#{k}", v
        end
      else
        super arg
      end
    end

    # Override to_s to display a friendly error message
    def to_s
      message
    end

    def message
      if @message.nil?
        msg = "Error message: the server returns an error"
      else
        msg = @message
      end

      msg += "\nHTTP status code: #{code}" if code
      msg += "\nResponse headers: #{response_headers}" if response_headers
      msg += "\nResponse body: #{response_body}" if response_body

      msg
    end

  end
end
